"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from ...tl.tlobject import TLRequest
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeInputConferenceCall, TypeInputConferenceMediaTrack, TypeInputConferenceParticipant, TypeInputPeer



class BanConferenceParticipantRequest(TLRequest):
    CONSTRUCTOR_ID = 0x799a53fc
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall', peer: 'TypeInputPeer'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference
        self.peer = peer

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'BanConferenceParticipantRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer
        }

    def _bytes(self):
        return b''.join((
            b'\xfcS\x9ay',
            self.conference._bytes(),
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        _peer = reader.tgread_object()
        return cls(conference=_conference, peer=_peer)


class CreateConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0x350ba3bd
    SUBCLASS_OF_ID = 0x83c38602

    def __init__(self, version: str, random_id: int=None, name: Optional[str]=None):
        """
        :returns ConferenceCreated: Instance of ConferenceCreated.
        """
        self.version = version
        self.random_id = random_id if random_id is not None else int.from_bytes(os.urandom(8), 'big', signed=True)
        self.name = name

    def to_dict(self):
        return {
            '_': 'CreateConferenceCallRequest',
            'version': self.version,
            'random_id': self.random_id,
            'name': self.name
        }

    def _bytes(self):
        return b''.join((
            b'\xbd\xa3\x0b5',
            struct.pack('<I', (0 if self.name is None or self.name is False else 1)),
            self.serialize_bytes(self.version),
            struct.pack('<q', self.random_id),
            b'' if self.name is None or self.name is False else (self.serialize_bytes(self.name)),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _version = reader.tgread_string()
        _random_id = reader.read_long()
        if flags & 1:
            _name = reader.tgread_string()
        else:
            _name = None
        return cls(version=_version, random_id=_random_id, name=_name)


class DiscardConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0x51620842
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference

    def to_dict(self):
        return {
            '_': 'DiscardConferenceCallRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference
        }

    def _bytes(self):
        return b''.join((
            b'B\x08bQ',
            self.conference._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        return cls(conference=_conference)


class GetActiveConferenceCallsRequest(TLRequest):
    CONSTRUCTOR_ID = 0xc3f93e37
    SUBCLASS_OF_ID = 0xa95c83d7

    def __init__(self, limit: int, offset: Optional[str]=None):
        """
        :returns ActiveConferenceCalls: Instance of ActiveConferenceCalls.
        """
        self.limit = limit
        self.offset = offset

    def to_dict(self):
        return {
            '_': 'GetActiveConferenceCallsRequest',
            'limit': self.limit,
            'offset': self.offset
        }

    def _bytes(self):
        return b''.join((
            b'7>\xf9\xc3',
            struct.pack('<I', (0 if self.offset is None or self.offset is False else 1)),
            struct.pack('<i', self.limit),
            b'' if self.offset is None or self.offset is False else (self.serialize_bytes(self.offset)),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _limit = reader.read_int()
        if flags & 1:
            _offset = reader.tgread_string()
        else:
            _offset = None
        return cls(limit=_limit, offset=_offset)


class GetBannedConferenceParticipantsRequest(TLRequest):
    CONSTRUCTOR_ID = 0x7d69c24c
    SUBCLASS_OF_ID = 0x76747d21

    def __init__(self, conference: 'TypeInputConferenceCall'):
        """
        :returns BannedConferenceParticipants: Instance of BannedConferenceParticipants.
        """
        self.conference = conference

    def to_dict(self):
        return {
            '_': 'GetBannedConferenceParticipantsRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference
        }

    def _bytes(self):
        return b''.join((
            b'L\xc2i}',
            self.conference._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        return cls(conference=_conference)


class GetConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0x78ba8198
    SUBCLASS_OF_ID = 0x257f8161

    def __init__(self, conference: 'TypeInputConferenceCall'):
        """
        :returns conference.ConferenceCall: Instance of ConferenceCall.
        """
        self.conference = conference

    def to_dict(self):
        return {
            '_': 'GetConferenceCallRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference
        }

    def _bytes(self):
        return b''.join((
            b'\x98\x81\xbax',
            self.conference._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        return cls(conference=_conference)


class JoinConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0x2b04c211
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, version: str, conference: 'TypeInputConferenceCall'):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.version = version
        self.conference = conference

    def to_dict(self):
        return {
            '_': 'JoinConferenceCallRequest',
            'version': self.version,
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference
        }

    def _bytes(self):
        return b''.join((
            b'\x11\xc2\x04+',
            self.serialize_bytes(self.version),
            self.conference._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _version = reader.tgread_string()
        _conference = reader.tgread_object()
        return cls(version=_version, conference=_conference)


class LeaveConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0xe5f83a5e
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference

    def to_dict(self):
        return {
            '_': 'LeaveConferenceCallRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference
        }

    def _bytes(self):
        return b''.join((
            b'^:\xf8\xe5',
            self.conference._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        return cls(conference=_conference)


class MuteConferenceParticipantRequest(TLRequest):
    CONSTRUCTOR_ID = 0xd9a6240f
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall', participant: 'TypeInputConferenceParticipant', track: 'TypeInputConferenceMediaTrack'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference
        self.participant = participant
        self.track = track

    def to_dict(self):
        return {
            '_': 'MuteConferenceParticipantRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference,
            'participant': self.participant.to_dict() if isinstance(self.participant, TLObject) else self.participant,
            'track': self.track.to_dict() if isinstance(self.track, TLObject) else self.track
        }

    def _bytes(self):
        return b''.join((
            b'\x0f$\xa6\xd9',
            self.conference._bytes(),
            self.participant._bytes(),
            self.track._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        _participant = reader.tgread_object()
        _track = reader.tgread_object()
        return cls(conference=_conference, participant=_participant, track=_track)


class RemoveConferenceParticipantRequest(TLRequest):
    CONSTRUCTOR_ID = 0x2d3e2518
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall', participant: 'TypeInputConferenceParticipant'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference
        self.participant = participant

    def to_dict(self):
        return {
            '_': 'RemoveConferenceParticipantRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference,
            'participant': self.participant.to_dict() if isinstance(self.participant, TLObject) else self.participant
        }

    def _bytes(self):
        return b''.join((
            b'\x18%>-',
            self.conference._bytes(),
            self.participant._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        _participant = reader.tgread_object()
        return cls(conference=_conference, participant=_participant)


class ResolveConferenceCallRequest(TLRequest):
    CONSTRUCTOR_ID = 0x3af930b4
    SUBCLASS_OF_ID = 0x257f8161

    def __init__(self, slug: str):
        """
        :returns conference.ConferenceCall: Instance of ConferenceCall.
        """
        self.slug = slug

    def to_dict(self):
        return {
            '_': 'ResolveConferenceCallRequest',
            'slug': self.slug
        }

    def _bytes(self):
        return b''.join((
            b'\xb40\xf9:',
            self.serialize_bytes(self.slug),
        ))

    @classmethod
    def from_reader(cls, reader):
        _slug = reader.tgread_string()
        return cls(slug=_slug)


class SetConferenceRatingRequest(TLRequest):
    CONSTRUCTOR_ID = 0xc695c533
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, conference: 'TypeInputConferenceCall', rating: int, comment: str):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.conference = conference
        self.rating = rating
        self.comment = comment

    def to_dict(self):
        return {
            '_': 'SetConferenceRatingRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference,
            'rating': self.rating,
            'comment': self.comment
        }

    def _bytes(self):
        return b''.join((
            b'3\xc5\x95\xc6',
            self.conference._bytes(),
            struct.pack('<i', self.rating),
            self.serialize_bytes(self.comment),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        _rating = reader.read_int()
        _comment = reader.tgread_string()
        return cls(conference=_conference, rating=_rating, comment=_comment)


class UnbanConferenceParticipantRequest(TLRequest):
    CONSTRUCTOR_ID = 0xadd30f09
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, conference: 'TypeInputConferenceCall', peer: 'TypeInputPeer'):
        """
        :returns Bool: This type has no constructors.
        """
        self.conference = conference
        self.peer = peer

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))

    def to_dict(self):
        return {
            '_': 'UnbanConferenceParticipantRequest',
            'conference': self.conference.to_dict() if isinstance(self.conference, TLObject) else self.conference,
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer
        }

    def _bytes(self):
        return b''.join((
            b'\t\x0f\xd3\xad',
            self.conference._bytes(),
            self.peer._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _conference = reader.tgread_object()
        _peer = reader.tgread_object()
        return cls(conference=_conference, peer=_peer)

