"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from ...tl.tlobject import TLRequest
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeThirdPartyMessage



class RequestRequest(TLRequest):
    CONSTRUCTOR_ID = 0xc8520739
    SUBCLASS_OF_ID = 0x1f900a44

    def __init__(self, message: 'TypeThirdPartyMessage'):
        """
        :returns ThirdPartyReply: Instance of Reply.
        """
        self.message = message

    def to_dict(self):
        return {
            '_': 'RequestRequest',
            'message': self.message.to_dict() if isinstance(self.message, TLObject) else self.message
        }

    def _bytes(self):
        return b''.join((
            b'9\x07R\xc8',
            self.message._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _message = reader.tgread_object()
        return cls(message=_message)


class TellRequest(TLRequest):
    CONSTRUCTOR_ID = 0xa7ebdf75
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, message: 'TypeThirdPartyMessage'):
        """
        :returns Bool: This type has no constructors.
        """
        self.message = message

    def to_dict(self):
        return {
            '_': 'TellRequest',
            'message': self.message.to_dict() if isinstance(self.message, TLObject) else self.message
        }

    def _bytes(self):
        return b''.join((
            b'u\xdf\xeb\xa7',
            self.message._bytes(),
        ))

    @classmethod
    def from_reader(cls, reader):
        _message = reader.tgread_object()
        return cls(message=_message)

