"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeChat, TypeUser



class Message(TLObject):
    CONSTRUCTOR_ID = 0xd630e7f7
    SUBCLASS_OF_ID = 0xee042531

    def __init__(self, third_party_id: str, message_type: str, content: bytes):
        """
        Constructor for ThirdPartyMessage: Instance of Message.
        """
        self.third_party_id = third_party_id
        self.message_type = message_type
        self.content = content

    def to_dict(self):
        return {
            '_': 'Message',
            'third_party_id': self.third_party_id,
            'message_type': self.message_type,
            'content': self.content
        }

    def _bytes(self):
        return b''.join((
            b'\xf7\xe70\xd6',
            self.serialize_bytes(self.third_party_id),
            self.serialize_bytes(self.message_type),
            self.serialize_bytes(self.content),
        ))

    @classmethod
    def from_reader(cls, reader):
        _third_party_id = reader.tgread_string()
        _message_type = reader.tgread_string()
        _content = reader.tgread_bytes()
        return cls(third_party_id=_third_party_id, message_type=_message_type, content=_content)


class Reply(TLObject):
    CONSTRUCTOR_ID = 0x214899ac
    SUBCLASS_OF_ID = 0x1f900a44

    def __init__(self, message: 'TypeThirdPartyMessage', chats: List['TypeChat'], users: List['TypeUser']):
        """
        Constructor for ThirdPartyReply: Instance of Reply.
        """
        self.message = message
        self.chats = chats
        self.users = users

    def to_dict(self):
        return {
            '_': 'Reply',
            'message': self.message.to_dict() if isinstance(self.message, TLObject) else self.message,
            'chats': [] if self.chats is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.chats],
            'users': [] if self.users is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.users]
        }

    def _bytes(self):
        return b''.join((
            b'\xac\x99H!',
            self.message._bytes(),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.chats)),b''.join(x._bytes() for x in self.chats),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.users)),b''.join(x._bytes() for x in self.users),
        ))

    @classmethod
    def from_reader(cls, reader):
        _message = reader.tgread_object()
        reader.read_int()
        _chats = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _chats.append(_x)

        reader.read_int()
        _users = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _users.append(_x)

        return cls(message=_message, chats=_chats, users=_users)

TypeThirdPartyMessage = Message
TypeThirdPartyReply = Reply
