"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeChat, TypeDocument, TypeUser, TypeUserFull, TypeUserFullCustom



class SavedMusic(TLObject):
    CONSTRUCTOR_ID = 0x34a2f297
    SUBCLASS_OF_ID = 0xf813ae37

    def __init__(self, count: int, documents: List['TypeDocument']):
        """
        Constructor for users.SavedMusic: Instance of either SavedMusicNotModified, SavedMusic.
        """
        self.count = count
        self.documents = documents

    def to_dict(self):
        return {
            '_': 'SavedMusic',
            'count': self.count,
            'documents': [] if self.documents is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.documents]
        }

    def _bytes(self):
        return b''.join((
            b'\x97\xf2\xa24',
            struct.pack('<i', self.count),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.documents)),b''.join(x._bytes() for x in self.documents),
        ))

    @classmethod
    def from_reader(cls, reader):
        _count = reader.read_int()
        reader.read_int()
        _documents = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _documents.append(_x)

        return cls(count=_count, documents=_documents)


class SavedMusicNotModified(TLObject):
    CONSTRUCTOR_ID = 0xe3878aa4
    SUBCLASS_OF_ID = 0xf813ae37

    def __init__(self, count: int):
        """
        Constructor for users.SavedMusic: Instance of either SavedMusicNotModified, SavedMusic.
        """
        self.count = count

    def to_dict(self):
        return {
            '_': 'SavedMusicNotModified',
            'count': self.count
        }

    def _bytes(self):
        return b''.join((
            b'\xa4\x8a\x87\xe3',
            struct.pack('<i', self.count),
        ))

    @classmethod
    def from_reader(cls, reader):
        _count = reader.read_int()
        return cls(count=_count)


class UserFull(TLObject):
    CONSTRUCTOR_ID = 0x594c64b5
    SUBCLASS_OF_ID = 0x83df9df5

    def __init__(self, full_user: 'TypeUserFull', chats: List['TypeChat'], users: List['TypeUser'], customInfo: Optional['TypeUserFullCustom']=None):
        """
        Constructor for users.UserFull: Instance of UserFull.
        """
        self.full_user = full_user
        self.chats = chats
        self.users = users
        self.customInfo = customInfo

    def to_dict(self):
        return {
            '_': 'UserFull',
            'full_user': self.full_user.to_dict() if isinstance(self.full_user, TLObject) else self.full_user,
            'chats': [] if self.chats is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.chats],
            'users': [] if self.users is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.users],
            'customInfo': self.customInfo.to_dict() if isinstance(self.customInfo, TLObject) else self.customInfo
        }

    def _bytes(self):
        return b''.join((
            b'\xb5dLY',
            struct.pack('<I', (0 if self.customInfo is None or self.customInfo is False else 1)),
            self.full_user._bytes(),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.chats)),b''.join(x._bytes() for x in self.chats),
            b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.users)),b''.join(x._bytes() for x in self.users),
            b'' if self.customInfo is None or self.customInfo is False else (self.customInfo._bytes()),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _full_user = reader.tgread_object()
        reader.read_int()
        _chats = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _chats.append(_x)

        reader.read_int()
        _users = []
        for _ in range(reader.read_int()):
            _x = reader.tgread_object()
            _users.append(_x)

        if flags & 1:
            _customInfo = reader.tgread_object()
        else:
            _customInfo = None
        return cls(full_user=_full_user, chats=_chats, users=_users, customInfo=_customInfo)

